name: dart_flex
version: 0.8.35
author: Frank Pepermans <frank@igindo.com>
description: Flex-like components in Dart
homepage: https://github.com/frankpepermans/dart_flex
dependencies:
  barback: any
  browser: any
  crypto: any
  observe: any
  xml: any
transformers:
- dart_flex/src/transformers/uiml_transformer
- observe/transformer
