name: dart_flex
version: 0.8.10+3
author: Frank Pepermans <frank@igindo.com>
description: Flex-like components in Dart
homepage: https://github.com/frankpepermans/dart_flex
dependencies:
  browser: '>=0.9.0'
  observe: '>=0.9.0'
