name: dart_flex
version: 0.5.1
author: Frank Pepermans <frank@igindo.com>
description: Flex-like components in Dart
homepage: https://github.com/frankpepermans/dart_flex
dependencies:
  browser: any
  observe: '>=0.8.10+3'
